name: 'Kebechet'
description: 'Action to trigger Kebechet repository manager.'
author: 'Marek Cermak'

inputs: 
  ssh_key:
    description: 'Kebechet GitHub SSH private key (base64 encoded)'
    required: true
  config:
    description: 'Path to the Kebechet configuration file'
    default: '.thoth.yaml'
    required: true
runs:
  using: 'docker'
  image: 'docker://thothstation/kebechet-github-action:latest'
  args:
    - '${{ inputs.config }}'
  env:
    # Credentials
    KEBECHET_SSH_PRIVATE_KEY: '${{ inputs.ssh_key }}'
    # Additional configuration
    KEBECHET_VERBOSE: '1'
