name: Docker Image CI

on:
  push:
    branches:
    - latest
    - v*

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}
        if [ "$IMAGE_TAG" == "master" ]; then
          IMAGE_TAG='latest'
        fi

        docker build . --file build/Dockerfile --tag thothstation/kebechet-github-action:${IMAGE_TAG}
      
    - name: Login to the DockerHub
      run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push the Docker image to the registry
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}
        if [ "$IMAGE_TAG" == "master" ]; then
          IMAGE_TAG='latest'
        fi

        docker push thothstation/kebechet-github-action:${IMAGE_TAG}
